---
title: "ALHS Common Operational Picture"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(zoo)
library(pins)
library(lubridate)

salt_board <- board_connect(
  auth = "manual",
  server = Sys.getenv("CONNECT_SERVER"),
  key = Sys.getenv("CONNECT_API_KEY")
)

## Colors =====================================================================

cchmc_light_green <- "#A1CA3C"
cchmc_dark_green <- "#76BC44"
cchmc_light_blue <- "#9BD3DD"
cchmc_medium_blue <- "#71C5E8"
cchmc_dark_blue <- "#00AEC7"
cchmc_light_purple <- "#CA5699"
cchmc_medium_purple <- "#9E4679"
cchmc_dark_purple <- "#83286B"
cchmc_pink <- "#E64479"
cchmc_dark_grey <- "#55575A"

## Load data ==================================================================

cop <- pin_read(salt_board, "fli6sh_131289@cchmc.org/cop_measures")
pop <- pin_read(salt_board, "fli6sh_131289@cchmc.org/Hamco_population")
ref <- pin_read(salt_board, "fli6sh_131289@cchmc.org/referrals")
reg <- pin_read(salt_board, "fli6sh_131289@cchmc.org/registry")

## Functions ==================================================================

movavgchart <- function(df, title, ylim){
  x <- ggplot(
    df, 
    aes(x = ContactMonth, y = value, color = name, linetype = name)
  ) +
    geom_line(linewidth = 1) +
    labs(
      x = NULL, 
      y = "Encounters per 100,000 children", 
      color = NULL,
      linetype = NULL,
      title = title
    ) +
    scale_y_continuous(limits = c(0, ylim), breaks = seq(0, ylim, 20)) +
    scale_x_date(
      limits = c(as.Date("2022-01-01"), floor_date(today()-31, "month"))
      ) +
    scale_color_manual(values = c(cchmc_dark_blue, cchmc_pink)) +
    theme_minimal() +
    theme(plot.title = element_text(hjust = .5)) +
    geom_point(aes(x = ContactMonth, y = value, size = name)) +
    scale_size_manual(values = c(3, .5)) +
    guides(size = "none")
  ggplotly(x) 
}

pchart <- function(df, title, limit){
  x <- ggplot(
    df, 
    aes(x = ContactMonth, y = value, color = name, linetype = name)
  ) +
    geom_line(linewidth = 1) +
    labs(
      x = NULL, 
      y = "%", 
      title = title,
      size = NULL
    ) +
    scale_x_continuous(breaks = unique(df$ContactMonth), labels = NULL) +
    scale_y_continuous(
      limits = c(0, limit/100),
      breaks = seq(0, .2*(limit/100)%/%.2, .1),
      labels = seq(0, 20*limit%/%20, 10)
      ) +
    scale_color_manual(
      values = c(cchmc_pink, cchmc_pink, cchmc_dark_blue, cchmc_pink)
      ) +
    scale_linetype_manual(values = c("solid", "dashed", "solid", "dashed")) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = .5),
      axis.text.x = element_text(angle = 90)
      ) +
    geom_point(aes(x = ContactMonth, y = value, size = name)) +
    scale_size_manual(values = c(0.25, 0.25, 3, 0.25)) +
    guides(size = "none", linetype = "none", color = "none")
  ggplotly(x) 
}

readmit_frame <- function(df, days){
  x <- df |>
    select(ContactMonth, Encounters, contains(days))
  colnames(x) <- c("ContactMonth", "Admissions", "Readmissions", "Rate")
  x <- x |>
    mutate(
      BaseTotal = sum(Admissions[year(ContactMonth) < 2024]),
      BaseReadmit = sum(Readmissions[year(ContactMonth) < 2024]),
      Centerline = BaseReadmit/BaseTotal,
      sigma = sqrt(Centerline*(1-Centerline)/Admissions),
      UCL = Centerline + 3*sigma,
      UCL = ifelse(UCL > 1, 1, UCL),
      LCL = Centerline - 3*sigma,
      LCL = ifelse(LCL < 0, 0, LCL)
    ) |>
    filter(!is.na(Rate)) |>
    pivot_longer(cols = c(Centerline, Rate, UCL, LCL))
}

refer_chart <- function(df, program, title){
  x <- df |>
    filter(
      Program == program,
      ReferMonth <= today()-31
      )
  y <- ggplot(x, aes(x = ReferMonth, y = value, color = name, linetype = name)) +
    geom_line(linewidth = 1) +
    labs(x = NULL, y = NULL, title = title) +
    scale_x_date(
      breaks = unique(x$ReferMonth),
      labels = paste(
        year(unique(x$ReferMonth)),
        month(unique(x$ReferMonth)),
        sep = "-"
      )
    ) +
    scale_y_continuous(limits = c(0, ifelse(program == "HELP", 120, 20))) +
    scale_color_manual(
      values = c(cchmc_pink, cchmc_pink, cchmc_dark_blue, cchmc_pink)
    ) +
    scale_linetype_manual(values = c("solid", "dashed", "solid", "dashed")) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 90),
      plot.title = element_text(hjust = .5)
    ) +
    geom_point(aes(x = ReferMonth, y = value, size = name)) +
    scale_size_manual(values = c(0.25, 0.25, 3, 0.25)) +
    guides(linetype = "none", color = "none", size = "none")

  ggplotly(y)
}

## Dateframe =================================================================

months <- seq.Date(
    as.Date("2022-01-01"), 
    floor_date(today()-31, "month"), 
    by = "month"
    )
dateframe <- data.frame(
  ContactMonth = rep(months, 282),
  Neighborhood = rep(unique(pop$Neighborhood), each = 3, length(months)),
  encounter_type = rep(c("Admission", "ED", "UC"), 3196)
)
  
hood_rates <- filter(cop, ContactMonth < today()-30) |>
  mutate(Months = length(unique(ContactMonth))) |>
  group_by(Neighborhood, encounter_type) |>
  reframe(Encounters = sum(Encounters)) |>
  right_join(dateframe |> distinct(Neighborhood, encounter_type)) |>
  mutate(
    Encounters = coalesce(Encounters, 0),
    Rate = Encounters/length(unique(dateframe$ContactMonth))
    ) |>
  full_join(
    pop |> 
      group_by(SDN, Neighborhood) |> 
      reframe(Children = sum(Children))
    ) |>
  mutate(Rate = Rate*100000/Children)

```

Admissions {data-orientation=columns}
==================================


Column {data-width=900}
----------------------------------

### 

```{r}
admit_total <- filter(cop, encounter_type == "Admission") |>
  group_by(ContactMonth) |>
  reframe(Admissions = sum(Encounters)) |>
  arrange(ContactMonth) |>
  mutate(
    Rate = 100000*Admissions/sum(pop$Children),
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  )

movavgchart(admit_total, "Hamilton County", 250) |>
  layout(legend = list(x = 0.05, y = 0.95))
```

### 

```{r}
admit_race <- cop |>
  filter(
    encounter_type == "Admission",
    !is.na(Race)
    ) |>
  group_by(ContactMonth, Race) |>
  reframe(Admissions = sum(Encounters)) |>
  inner_join(pop |> group_by(Race) |> reframe(Children = sum(Children))) |>
  mutate(Rate = 100000*Admissions/Children) |> 
  arrange(Race, ContactMonth) |>
  group_by(Race) |>
  mutate(MA = rollmean(Rate, 12, align = "right", na.pad = TRUE))  |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  )

admit_race_chart <- ggplot(
  admit_race, 
  aes(x = ContactMonth, y = value, color = Race, linetype = name)
) +
  geom_line(linewidth = 1) +
  labs(
    x = NULL,
    y = "Encounters per 100,000 children",
    title = "By race",
    color = NULL,
    linetype = NULL
  ) +
  scale_y_continuous(limits = c(0, 300), breaks = seq(0, 240, 20)) +
  scale_x_date(
    limits = c(as.Date("2022-01-01"), floor_date(today()-31, "month"))
  ) +
  scale_color_manual(values = c(cchmc_dark_purple, cchmc_light_green)) +
  scale_linetype_manual(values = c("solid", "dashed")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5)) +
  geom_point(aes(x = ContactMonth, y = value, size = name)) +
  scale_size_manual(values = c(3, 0.5)) +
  guides(linetype = "none", size = "none")
ggplotly(admit_race_chart) |> layout(legend = list(x = .85, y = .95))
```

Column {data-width=900}
----------------------------------

### 

```{r}
admit_deprived <- cop |>
  filter(
    SDN,
    encounter_type == "Admission"
    ) |>
  group_by(ContactMonth, SDN) |>
  reframe(Admissions = sum(Encounters)) |>
  inner_join(pop |> group_by(SDN) |> reframe(Children = sum(Children))) |>
  arrange(ContactMonth) |>
  mutate(
    Rate = 100000*Admissions/Children,
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  )

movavgchart(admit_deprived, "Structually deprived neighborhoods", 250) |>
  layout(showlegend = FALSE)
```

###

```{r}
admit_avondale <- cop |>
  filter(
    Neighborhood == "Avondale",
    encounter_type == "Admission"
    ) |>
  group_by(ContactMonth, Neighborhood) |>
  reframe(Admissions = sum(Encounters)) |>
  right_join(
    filter(dateframe, Neighborhood == "Avondale") |>
      distinct(Neighborhood, ContactMonth)
    ) |>
  mutate(Admissions = coalesce(Admissions, 0))  |>
  inner_join(
    pop |> 
      group_by(Neighborhood) |> 
      reframe(Children = sum(Children))
    ) |>
  arrange(ContactMonth) |>
  mutate(
    Rate = 100000*Admissions/Children,
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  ) 

movavgchart(admit_avondale, "Avondale", 250) |>
  layout(showlegend = FALSE)
```


Column {data-width=600}
----------------------------------

###

```{r}
hood_admit <- hood_rates |>
  filter(
    encounter_type == "Admission",
    Neighborhood != "Milford",
    Encounters > 0
    ) |>
  arrange(-Rate) |>
  mutate(rn = row_number()) |>
  filter(rn <= 50)

hood_admit_plot <- ggplot(
  hood_admit, 
  aes(x = reorder(Neighborhood, Rate), y = Rate)
  ) +
  geom_bar(stat = "identity", fill = cchmc_light_blue) +
  coord_flip() +
  labs(
    x = NULL, 
    y = "Encounters per month\nper 100,000 children", 
    title = "Top 50 rates by neighborhood"
    ) +
  scale_y_continuous(breaks = seq(0, 80, 20)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5))
ggplotly(hood_admit_plot)

```



ED visits {data-orientation=columns}
===============================================

Column {data-width=900}
----------------------------------

###

```{r}
ed_total <- filter(cop, encounter_type == "ED") |>
  group_by(ContactMonth) |>
  reframe(EDVisits = sum(Encounters)) |>
  arrange(ContactMonth) |>
  mutate(
    Rate = 100000*EDVisits/sum(pop$Children),
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  )

movavgchart(ed_total, "Hamilton County", 321) |>
  layout(legend = list(x = 0.05, y = 0.95))
```

###

```{r}
ed_race <- cop |>
  filter(
    !is.na(Race),
    encounter_type == "ED"
    ) |>
  group_by(ContactMonth, Race) |>
  reframe(EDVisits = sum(Encounters)) |>
  inner_join(pop |> group_by(Race) |> reframe(Children = sum(Children))) |>
  arrange(ContactMonth, Race) |>
  group_by(Race) |>
  mutate(
    Rate = EDVisits*100000/Children,
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA)

ed_race_chart <- ggplot(
  ed_race,
  aes(x = ContactMonth, y = value, color = Race, linetype = name)
) +
  geom_line(linewidth = 1) +
  labs(
    x = NULL,
    y = "Encounters per 100,000 children",
    title = "By race",
    color = NULL,
    linetype = NULL
  ) +
  scale_y_continuous(limits = c(0, 321), breaks = seq(0, 320, 20)) +
  scale_x_date(
    limits = c(as.Date("2022-01-01"), floor_date(today()-31, "month"))
  ) +
  scale_color_manual(values = c(cchmc_dark_purple, cchmc_light_green)) +
  scale_linetype_manual(values = c("dashed", "solid")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5)) +
  geom_point(aes(x = ContactMonth, y = value, size = name)) +
  scale_size_manual(values = c(0.25, 3)) +
  guides(linetype = "none", size = "none")
ggplotly(ed_race_chart) |> layout(legend = list(x = .85, y = .95))
```

Column {data-width=900}
----------------------------------

###

```{r}
ed_deprived <- cop |>
  filter(
    SDN,
    encounter_type == "ED"
    ) |>
  group_by(ContactMonth, SDN) |>
  reframe(EDVisits = sum(Encounters)) |>
  inner_join(pop |> group_by(SDN) |> reframe(Children = sum(Children))) |>
  arrange(ContactMonth) |>
  mutate(
    Rate = EDVisits*100000/Children,
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  )

movavgchart(ed_deprived, "Structually deprived neighborhoods", 321) |>
  layout(showlegend = FALSE)
```

###

```{r}
ed_avondale <- cop |>
  filter(
    Neighborhood == "Avondale",
    encounter_type == "ED"
    ) |>
  group_by(ContactMonth, Neighborhood) |>
  reframe(Encounters = sum(Encounters)) |>
  right_join(
    filter(dateframe, Neighborhood == "Avondale") |>
      distinct(Neighborhood, ContactMonth)
    ) |>
  mutate(Encounters = coalesce(Encounters, 0))  |>
  inner_join(
    pop |> 
      group_by(Neighborhood) |> 
      reframe(Children = sum(Children))
    ) |>
  arrange(ContactMonth) |>
  mutate(
    Rate = 100000*Encounters/Children,
    MA = rollmean(Rate, 12, align = "right", na.pad = TRUE)
  ) |>
  pivot_longer(Rate:MA) |>
  mutate(
    name = ifelse(name == "MA", "12-month moving average", name),
    name = factor(name, levels = c("Rate", "12-month moving average"))
  ) 

movavgchart(ed_avondale, "Avondale", 325) |>
  layout(showlegend = FALSE)
```

Column {data-width=600}
----------------------------------
###
```{r}
hood_ed <- hood_rates |>
  filter(
    encounter_type == "ED",
    Neighborhood != "Milford",
    Encounters > 0
    ) |>
  arrange(-Rate) |>
  mutate(rn = row_number()) |>
  filter(rn <= 50)

hood_ed_plot <- ggplot(
  hood_ed, 
  aes(x = reorder(Neighborhood, Rate), y = Rate)
  ) +
  geom_bar(stat = "identity", fill = cchmc_light_blue) +
  coord_flip() +
  labs(
    x = NULL, 
    y = "Encounters per month\nper 100,000 children", 
    title = "Top 50 rates by neighborhood"
    ) +
  scale_y_continuous(breaks = seq(0, 80, 20)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5))
ggplotly(hood_ed_plot)
```


Readmissions
===============================================

Row
----------------------------------

### Admissions only

```{r}
readmit_total <- filter(cop, encounter_type == "Admission") |>
  group_by(ContactMonth) |>
  reframe(across(c(Encounters, Readmit30:Readmit365), sum)) |>
  mutate(
    Readmit30Rate = ifelse(ContactMonth < today()-60, Readmit30/Encounters, NA),
    Readmit90Rate = ifelse(ContactMonth < today()-120, Readmit90/Encounters, NA),
    Readmit365Rate = ifelse(
      ContactMonth < today()-395,
      Readmit365/Encounters,
      NA
      ),
  )

readmit_ED <- filter(cop, encounter_type == "Admission") |>
  group_by(ContactMonth) |>
  reframe(across(c(Encounters, ReadmitED30:ReadmitED365), sum)) |>
  mutate(
    ReadmitED30Rate = ifelse(
      ContactMonth < today()-60,
      ReadmitED30/Encounters,
      NA
      ),
    ReadmitED90Rate = ifelse(
      ContactMonth < today()-120,
      ReadmitED90/Encounters,
      NA
      ),
    ReadmitED365Rate = ifelse(
      ContactMonth < today()-395,
      ReadmitED365/Encounters,
      NA
      ),
  )

readmit_30 <- readmit_frame(readmit_total, "30")

pchart(readmit_30, "30 days", 21)

```


### Including ED visits
```{r}
readmited_30 <- readmit_frame(readmit_ED, "30")

pchart(readmited_30, "30 days", 21)

```

Row
----------------------------------

###
```{r}
readmit_90 <- readmit_frame(readmit_total, "90")

pchart(readmit_90, "90 days", 44)
```

###
```{r}
readmited_90 <- readmit_frame(readmit_ED, "90")

pchart(readmited_90, "90 days", 44)
```

Row
----------------------------------

###
```{r}
readmit_365 <- readmit_frame(readmit_total, "365")

pchart(readmit_365, "365 days", 74) |>
  layout(showlegend = FALSE)
```

###
```{r}
readmited_365 <- readmit_frame(readmit_ED, "365")

pchart(readmited_365, "365 days", 74) |>
  layout(showlegend = FALSE)
```


Referrals
==================================

Row
----------------------------------
### All referrals

```{r}
#| echo: false

ref_all <- ref |>
  group_by(Program, ReferMonth) |>
  reframe(Referrals = sum(Referrals)) |>
  group_by(Program) |>
  mutate(
    BaseRefers = sum(Referrals[year(ReferMonth) < 2024]),
    Months = length(unique(ReferMonth[year(ReferMonth) < 2024])),
    CL = BaseRefers/Months,
    UCL = CL + (3*sqrt(CL)),
    LCL = CL - (3*sqrt(CL)),
    LCL = ifelse(LCL < 0, 0, LCL),
    ReferMonth = ymd(ReferMonth)
  ) |>
  pivot_longer(cols = c(Referrals, CL:LCL))



ref_sdn <- filter(ref, SDN) |>
  group_by(Program, ReferMonth) |>
  reframe(Referrals = sum(Referrals)) |>
  right_join(ref_all |> distinct(ReferMonth, Program)) |>
  mutate(Referrals = coalesce(Referrals, 0)) |>
  group_by(Program) |>
  mutate(
    BaseRefers = sum(Referrals[year(ReferMonth) < 2024]),
    Months = length(unique(ReferMonth[year(ReferMonth) < 2024])),
    CL = BaseRefers/Months,
    UCL = CL + (3*sqrt(CL)),
    LCL = CL - (3*sqrt(CL)),
    LCL = ifelse(LCL < 0, 0, LCL),
    ReferMonth = ymd(ReferMonth)
  ) |>
  pivot_longer(cols = c(Referrals, CL:LCL))

refer_chart(
  ref_all,
  "CLEAR",
  "Collaboration to Lessen Environmental Asthma Risks"
  )

```


### Structurally Deprived Neighborhoods

```{r}
#| echo: false

refer_chart(
  ref_sdn,
  "CLEAR",
  "Collaboration to Lessen Environmental Asthma Risks"
  )

```


Row
----------------------------------
### All referrals
```{r}
#| echo: false
refer_chart(ref_all, "HELP", "Child Health Law Partnership")
```
### Structurally Disadvantaged Neighborhoods

```{r}
#| echo: false

refer_chart(ref_sdn, "HELP", "Child Health Law Partnership")
```

Engagement
==================================
Row
----------------------------------

###
```{r}

reg_tot <- reg |>
  group_by(Date) |>
  reframe(Registry = sum(Registry))

reg_pat <- ggplot(reg_tot, aes(x = Date, y = Registry)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(x = NULL, y = NULL, title = "Patients on Asthma Registry") +
  scale_x_date(
    limits = c(min(reg$Date), as.Date("2024-10-01")),
    breaks = reg$Date[reg$Date <= as.Date("2024-10-01")]
    ) +
  scale_y_continuous(
    limits = c(45000, 65000),
    breaks = seq(48000, 64000, 4000),
    labels = format(seq(48000, 64000, 4000), big.mark = ",")
    ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  geom_point(aes(x = Date, y = Registry), size = 3, color = cchmc_dark_blue) +
  annotate("text", x = as.Date("2023-06-01"), y = 55000, size = 36, label = "FAKE DATA")
ggplotly(reg_pat)





```

###



```{r}
reg_tot$VisitRate <- runif(nrow(reg_tot))*100

reg_visit <- ggplot(reg_tot, aes(x = Date, y = VisitRate)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = "%",
    title = "% of patients with visit in past 12 months") +
  scale_x_date(breaks = reg$Date) +
  scale_y_continuous(breaks = NULL) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  geom_point(aes(x = Date, y = VisitRate), size = 3, color = cchmc_dark_blue) +
  annotate("text", x = as.Date("2023-06-01"), y =.5, size = 40, label = "FAKE DATA")
ggplotly(reg_visit)

```

 Row
----------------------------------

###
```{r}
#| echo: false

action <- data.frame(
  Date = seq.Date(
    as.Date("2022-01-01"),
    as.Date("2024-10-01"),
    by = "month"
    ),
  Innovation = runif(34)*5,
  Attendance = sample(10:100, 34),
  Trained = sort(sample(10:100, 34))
)

inn <- ggplot(action, aes(x = Date, y = Innovation)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Overall innovation scale score"
    ) +
  scale_x_date(breaks = action$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  geom_point(aes(x = Date, y = Innovation), size = 3, color = cchmc_dark_blue) +
  annotate("text", x = as.Date("2023-06-01"), y = 2.5, size = 24, label = "FAKE DATA")
ggplotly(inn)

```

###

```{r}
#| echo:false
att <- ggplot(action, aes(x = Date, y = Attendance)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Attendance at AP calls"
    ) +
  scale_x_date(breaks = action$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  geom_point(aes(x = Date, y = Attendance), size = 3, color = cchmc_dark_blue) +
  annotate("text", x = as.Date("2023-06-01"), y = 50, size = 24, label = "FAKE DATA")
ggplotly(att)

```

###

```{r}
#| echo: false
qi <- ggplot(action, aes(x = Date, y = Trained)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Trained in QI"
    ) +
  scale_x_date(breaks = action$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  geom_point(aes(x = Date, y = Trained), size = 3, color = cchmc_dark_blue) +
  annotate("text", x = as.Date("2023-06-01"), y = 50, size = 24, label = "FAKE DATA")
ggplotly(qi)

```


Knowledge Generation
==================================
Row
----------------------------------
###

```{r}
#| echo: false

know <- data.frame(
  Date = seq.Date(
    as.Date("2022-01-01"),
    as.Date("2024-10-01"),
    by = "month"
    ),
  Papers = sort(sample(0:10, 34, replace = TRUE)),
  Grants = sort(sample(0:12, 34, replace = TRUE)),
  Studies = sort(sample(0:13, 34, replace = TRUE)),
  QI = sort(sample(0:15, 34, replace = TRUE)),
  Tests = sort(sample(0:20, 34, replace = TRUE))
)

pap <- ggplot(know, aes(x = Date, y = Papers)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Papers"
    ) +
  scale_x_date(breaks = know$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  annotate("text", x = as.Date("2023-06-01"), y = 5, size = 32, label = "FAKE DATA")
ggplotly(pap)

```

###

```{r}
#| echo: false

grant <- ggplot(know, aes(x = Date, y = Grants)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Grants"
    ) +
  scale_x_date(breaks = know$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  annotate("text", x = as.Date("2023-06-01"), y = 7, size = 32, label = "FAKE DATA")
ggplotly(grant)

```

Row
----------------------------------

###

```{r}
#| echo: false

stud <- ggplot(know, aes(x = Date, y = Studies)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Studies"
    ) +
  scale_x_date(breaks = know$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  annotate("text", x = as.Date("2023-06-01"), y = 7, size = 24, label = "FAKE DATA")
ggplotly(stud)
```

###

```{r}
#| echo: false

qip <- ggplot(know, aes(x = Date, y = QI)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Quality Improvement Projects"
  ) +
  scale_x_date(breaks = know$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  annotate("text", x = as.Date("2023-06-01"), y = 8, size = 24, label = "FAKE DATA")
ggplotly(qip)

```

###

```{r}
#| echo: false

test <- ggplot(know, aes(x = Date, y = Tests)) +
  geom_line(linewidth = 1, color = cchmc_dark_blue) +
  labs(
    x = NULL,
    y = NULL,
    title = "Tests of change"
  ) +
  scale_x_date(breaks = know$Date) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = .5),
    axis.text.x = element_text(angle = 90)
  ) +
  annotate("text", x = as.Date("2023-06-01"), y = 10, size = 24, label = "FAKE DATA")
ggplotly(test)
```

